# -*- coding: utf-8 -*-
{
    'name': 'Bista Education Fee Master',
    'version': '1.0',
    'category': 'Bista Education',
    "sequence": 4,
    'summary': 'Manage Fee structure',
    'complexity': "easy",
    'description': """
            This module provide fee management system over OpenERP
    """,
    'author': 'Bista Solutions',
    'website': 'bistasolutions.com',
    'images': [],
    'depends': ['base','account','account_voucher'],
    'data': ['security/fees_security.xml',
             'security/ir.model.access.csv',
             'view/fees_structure_view.xml',
             'view/fee_calculation_view.xml',
             'view/student_fee_invoice_view.xml',
             'view/Fee_payment_type.xml',
             'view/fee_history_view.xml',
             'view/student_fee_payment_view.xml',
             'view/product_fees_view.xml',
             'view/fees_discount_view.xml',
             'view/product_fees_view.xml',
             'view/fees_discount_view.xml',
             'view/sequence_view.xml',
             'view/fee_next_year_advance_view.xml',
             'view/resend_payfort_voucher_view.xml',
             'wizard/parent_payment_report_wiz.xml',
             'wizard/student_payment_report_wiz.xml',
             'wizard/resend_pay_fort_link.xml',
             'wizard/payfort_link_reminder_view.xml',
             'wizard/reconcile_advance_payment.xml',
             'report/parent_payment_report.xml',
             'report/student_payment_report.xml',
             'report/fees_receipt.xml',
	         'view/menu_view.xml'],
    'demo': [],
    'css': [],
    'qweb': [],
    'js': [],
    'test': [],
    'images': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
